package com.htueko.tenki.core.util

import timber.log.Timber

/**
 * A global logging utility for the Tenki application.
 *
 * This object wraps the [Timber] library to provide consistent, tagged logging
 * throughout the app. It simplifies the initialization process and ensures that
 * all logs follow a specific format and naming convention.
 *
 * ### Features:
 * - Prefixes all tags with `tenki_`.
 * - Automatically appends class and method names to the log tag for easier debugging.
 */
object AppLogger {
    /**
     * Initializes the logging tree.
     * * This should typically be called once in the `onCreate` method of your
     * [Application] class, usually wrapped in a `BuildConfig.DEBUG` check.
     */
    fun init() {
        setupTimber()
    }

    /**
     * Configures a custom [Timber.DebugTree] for the application.
     *
     * The custom tree performs two main modifications:
     * 1. **Tag Prefixing**: Modifies the log output to include a "tenki_" prefix.
     * 2. **Metadata Injection**: Enhances the tag with the source file's class and method name.
     *
     * @see [Timber GitHub](https://github.com/JakeWharton/timber)
     */
    private fun setupTimber() {
        Timber.plant(
            object : Timber.DebugTree() {
                /**
                 * Modifies the log tag before it is sent to the console.
                 * * @param priority Log level (e.g., [android.util.Log.DEBUG]).
                 * @param tag The original tag generated by Timber.
                 * @param message The actual log content.
                 * @param t An optional [Throwable] for stack traces.
                 */
                override fun log(
                    priority: Int,
                    tag: String?,
                    message: String,
                    t: Throwable?,
                ) {
                    super.log(priority, "tenki_$tag", message, t)
                }

                /**
                 * Creates a tag for the log by extracting information from the stack trace.
                 * * @param element The [StackTraceElement] representing the log's call site.
                 * @return A string in the format "ClassName:MethodName".
                 */
                override fun createStackElementTag(element: StackTraceElement): String =
                    String.format(
                        "%s:%s",
                        element.className,
                        element.methodName,
                        element.lineNumber,
                        super.createStackElementTag(element),
                    )
            },
        )
    }
}